Protocol 002af3
Opentrons/Protocols pull request #1760
Opened 2020-10-16 21:42 UTC by Koeng101

Adds protocol for [002af3](https://docs.google.com/document/d/1FQS6kXFjTHEOsNNhIeFHY5R6FvL-BRs5sG65KXuocFQ/edit?ts=5f7b4881) to protocol library. Normally, `sample_count` would be used, but protocol specifically asked for a variable number of source columns, so this was programmed for that. 

Basic idea is to convert protocol built with the [Protocol Designer](https://s3.amazonaws.com/pf-upload-01/u-4256/0/2020-07-17/uo03r2t/Covid-19%2012%20columns%20.json) to be pythonized so that you can have a variable number of source columns. 

Two labwares - HARD-SHELL BIO-RAD PCR 384 WELL PLATE 50 UL and THERMO FISHER SCIENTIFIC ELUTION TUBES 96 WELL PLATE 650 UL - were not coded into this protocol. However, the current labwares should work to run the protocol in practice, but we may want to add those before merging.

2020-10-19 17:40 UTC, ncdiehl11 requested changes

2020-10-19 17:40 UTC, ncdiehl11 commented on protocols/002af3/002af3.ot2.apiv2.py
> +metadata = {"apiLevel": "2.3"}
please include author, source, protocolName fields to metadata

2020-11-17 23:00 UTC, chazmanc commented on protocols/002af3/002af3.ot2.apiv2.py
> +        'author': 'Chaz <chaz@opentrons.com>',
Feel free to put your name or you can change it to `Opentrons <protocols@opentrons.com>`

2020-11-17 23:01 UTC, chazmanc commented on protocols/002af3/002af3.ot2.apiv2.py
> +    column_count, cfxp, ctrlp = get_values(  # noqa: F821
The doc contains the links to the custom labware definitions; can you replace the holders with the correct definition and add the custom labware folder?

2020-11-18 23:02 UTC, merged