295c73
Opentrons/Protocols pull request #2084
Opened 2021-02-26 14:26 UTC by StevenPlonk

close #2013

2021-02-26 21:07 UTC, ncdiehl11 requested changes
Hey Steve, looks good, but I left a few (mostly stylistic) comments.

2021-02-26 21:07 UTC, ncdiehl11 commented on protocols/295c73/295c73.ot2.apiv2.py
> +    ETOH = reservoir.wells()[0]
generally, we reserve all capital variables for global variables. Let's change this to `etoh`

2021-02-26 21:07 UTC, ncdiehl11 commented on protocols/295c73/fields.json
> +      { "label": "YES", "value": "1" },
we can use the JSON values for booleans here, and not have to typecast them in the Python script. So, we can do:
```
{ "label": "YES", "value": true },
{ "label": "NO", "value": false }
```

2021-02-26 21:07 UTC, ncdiehl11 commented on protocols/295c73/295c73.ot2.apiv2.py
> +    if int(hold_pcr_plate_on_ice_until_block_reaches_98):
per my comment on `fields.json`, we can treat this variable as a boolean, and use:
```
if hold_pcr_plate_on_ice_until_block_reaches_98:
```

2021-03-03 14:24 UTC, chazmanc approved these changes

2021-03-03 14:24 UTC, chazmanc commented
closes #2014

2021-03-04 21:27 UTC, ncdiehl11 commented
changes reflected and merged in #2105

2021-03-04 21:27 UTC, closed without merging