Serial dilution update
Opentrons/Protocols pull request #3407
Opened 2022-03-09 20:12 UTC by john-c-lynch

##Overview

Deleted get_values function at top causing errors

2022-03-09 20:20 UTC, john-c-lynch commented
Same issue as before. make all wasn't run and the protobuilds folder causes problems then. Need to troubleshoot the make all on my local machine.

2022-03-09 21:01 UTC, chazmanc commented on protocols/customizable_serial_dilution_ot2/customizable_serial_dilution.ot2.apiv2.py
> +    'apiLevel': '2.2'
why lower this?

2022-03-09 21:07 UTC, chazmanc requested changes
let's add a work in progress label to this PR (wip)

2022-03-09 21:07 UTC, chazmanc commented on protocols/customizable_serial_dilution_ot2/customizable_serial_dilution.ot2.apiv2.py
>              'total_mixing_volume', 'tip_use_strategy'
what happened to these?

2022-03-17 00:10 UTC, closed without merging

2022-03-17 00:10 UTC, john-c-lynch commented
Made prior to make script working locally. See dilution_v2 branch for further work